version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.1  # Replace with the latest version if needed
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false  # Disable security for development
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"  # Adjust JVM options
    ports:
      - "9200:9200"  # Elasticsearch REST API
      - "9300:9300"  # Elasticsearch transport API
    volumes:
      - esdata:/usr/share/elasticsearch/data  # Persistent data storage
    networks:
      - esnet

volumes:
  esdata:
    driver: local

networks:
  esnet:
    driver: bridge